name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run lint
      - name: Run npm build
        run: npm run build
  deploy:
    if: ${{ github.event_name == 'push' && !contains('#skip', join(github.event.commits.*.message)) }}
    needs: lint_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  notify_status:
    needs: [lint_and_build, deploy]
    if: ${{ !cancelled() && github.event_name == 'push' && !contains('#skip', join(github.event.commits.*.message)) }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    if: ${{ github.event_name == 'push' && !contains('#skip', join(github.event.commits.*.message)) }}
    needs: [lint_and_build, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
